services:
  nodo1:
    image: mongo:7.0
    container_name: nodo1
    command: ["mongod", "--replSet", "RP", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/nodo1:/data/db
    restart: unless-stopped

  nodo2:
    image: mongo:7.0
    container_name: nodo2
    command: ["mongod", "--replSet", "RP", "--bind_ip_all", "--port", "27018"]
    volumes:
      - ./data/nodo2:/data/db
    restart: unless-stopped

  nodo3:
    image: mongo:7.0
    container_name: nodo3
    command: ["mongod", "--replSet", "RP", "--bind_ip_all", "--port", "27019"]
    volumes:
      - ./data/nodo3:/data/db
    restart: unless-stopped

  arb:
    image: mongo:7.0
    container_name: arb
    command: ["mongod", "--replSet", "RP", "--bind_ip_all", "--port", "27020"]
    volumes:
      - ./data/arb:/data/db
    restart: unless-stopped

  app:
    build: .
    image: crud-mongo-app:latest
    container_name: crud-mongo-docker-kubernetes
    ports:
      - "4000:4000"
    depends_on:
      - nodo1
      - nodo2
      - nodo3
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://nodo1:27017,nodo2:27018,nodo3:27019/?replicaSet=RP
      - MONGODB_DB=prueba
      - MONGODB_COLLECTION=usuarios
    restart: unless-stopped

  mongo-init:
    image: mongo:7.0
    container_name: mongo-init
    depends_on:
      - nodo1
      - nodo2
      - nodo3
      - arb
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo "Esperando a que los nodos esten listos..."
        sleep 10
        mongosh --host nodo1:27017 --eval '
          try {
            rs.status();
            print("Replica Set ya inicializado");
          } catch (e) {
            rs.initiate({
              _id: "RP",
              members: [
                { _id: 0, host: "nodo1:27017", priority: 2 },
                { _id: 1, host: "nodo2:27018", priority: 1 },
                { _id: 2, host: "nodo3:27019", priority: 1 },
                { _id: 3, host: "arb:27020", arbiterOnly: true }
              ]
            });
            print("Replica Set inicializado con éxito");
          }
        '
