apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: mongo:7.0
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for MongoDB nodes to start..."
              sleep 15
              mongosh --host mongo-0.mongo-headless:27017 --eval '
                try {
                  rs.initiate({
                    _id: "RP",
                    members: [
                      { _id: 0, host: "mongo-0.mongo-headless:27017" },
                      { _id: 1, host: "mongo-1.mongo-headless:27017" },
                      { _id: 2, host: "mongo-2.mongo-headless:27017" }
                    ]
                  });
                  print("Replica Set initialized successfully.");
                } catch (err) {
                  if (err.message.includes("already initialized")) {
                    print("Replica Set already initialized. Proceeding safely...");
                  } else {
                    throw err;
                  }
                }
              '
      restartPolicy: OnFailure
  backoffLimit: 5
